// <auto-generated />
namespace Toptix.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updateCalculationType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateCalculationType));
        
        string IMigrationMetadata.Id
        {
            get { return "201212101358531_updateCalculationType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
