// <auto-generated />
namespace Toptix.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class charges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(charges));
        
        string IMigrationMetadata.Id
        {
            get { return "201211160957148_charges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
