// <auto-generated />
namespace Toptix.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class temp1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(temp1));
        
        string IMigrationMetadata.Id
        {
            get { return "201211091653486_temp1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
