// <auto-generated />
namespace Toptix.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cascadeOnDeleteFalse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cascadeOnDeleteFalse));
        
        string IMigrationMetadata.Id
        {
            get { return "201212241137240_cascadeOnDeleteFalse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
