// <auto-generated />
namespace Toptix.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class orderwithoutCurrency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderwithoutCurrency));
        
        string IMigrationMetadata.Id
        {
            get { return "201301101130451_orderwithoutCurrency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
