// <auto-generated />
namespace Toptix.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dropMailDaysGlobalParameters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropMailDaysGlobalParameters));
        
        string IMigrationMetadata.Id
        {
            get { return "201301031914471_dropMailDaysGlobalParameters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
